### PR TITLE
[Fix-3262][common]   When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled 

### LINKED ISSUE #3262: [Bug][dolphinscheduler-common]  When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled
When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled
eg:
image

yarn.application.status.address=http://ark1:8088/ws/v1/cluster/apps/%s

### PR DESCRIPTION
**Pull request by felix-thinkingdata**
[Bug][dolphinscheduler-common] When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled #3262

Tips
Thanks very much for contributing to Apache DolphinScheduler.
Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.
What is the purpose of the pull request

fix #3262

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Hi,

Please change the title according to the pr specifications[1]. Thx a lot~

[1] https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by felix-thinkingdata** [comment]
ok


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月22日(周三) 12:42
主题: Re: [apache/incubator-dolphinscheduler] fix bug #3262 When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Hi,
Please change the title according to the pr specifications[1]. Thx a lot~
[1] https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by yangyichao-mango** [comment]
Please add the for new code, sonar request 33.3% coverage for new code.
image

**Comment by felix-thinkingdata** [comment]
Is that ok？


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月22日(周三) 14:07
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Please add test case code the for new code, sonar request 33.3% coverage for new code.

**Comment by yangyichao-mango** [comment]
> Is that ok？ 原始邮件 发件人: Yichao Yang<notifications@github.com> 收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com> 抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com> 发送时间: 2020年7月22日(周三) 14:07 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Please add test case code the for new code, sonar request 33.3% coverage for new code. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Please add the 
`dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClientTest.java` to root pom surfire plugin to run this test.

**Comment by felix-thinkingdata** [comment]
Thank you very much


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月22日(周三) 14:55
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Is that ok？ 原始邮件 发件人: Yichao Yangnotifications@github.com 收件人: apache/incubator-dolphinschedulerincubator-dolphinscheduler@noreply.github.com 抄送: felix.wangfelix@thinkingdata.cn; State changestate_change@noreply.github.com 发送时间: 2020年7月22日(周三) 14:07 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Please add test case code the for new code, sonar request 33.3% coverage for new code. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
Please add the
 dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClientTest.java to root pom surfire plugin to run this test.

**Comment by felix-thinkingdata** [comment]
Can you review the code for me？




 原始邮件 
发件人: felix<felix@thinkingdata.cn>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>; apache/incubator-dolphinscheduler<reply@reply.github.com>
抄送: State change<state_change@noreply.github.com>
发送时间: 2020年7月22日(周三) 12:45
主题: Re: [apache/incubator-dolphinscheduler] fix bug #3262 When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


ok


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月22日(周三) 12:42
主题: Re: [apache/incubator-dolphinscheduler] fix bug #3262 When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Hi,
Please change the title according to the pr specifications[1]. Thx a lot~
[1] https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by yangyichao-mango** [comment]
Hi~,
There is a ut error, you can check this error.
image
Please try to remove some meaningful code smell of this pr.
image
https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=3264&resolved=false&types=CODE_SMELL

**Comment by yangyichao-mango** [comment]
Hi,
You can try to delete this test case from pom, and try run ci again to check whether it is the oom caused by `WorkerRegistryTest`.
image

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java [hunk 1]
```diff
@@ -33,66 +33,88 @@
...
 
 	/**
 	 * get http request content
+	 *
 	 * @param url url
 	 * @return http get request response content
 	 */
 	public static String get(String url){
-		CloseableHttpClient httpclient = HttpClients.createDefault();
+		boolean kerberState =PropertyUtils.getBoolean(Constants.HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE, false);
```
Comment (yangyichao-mango) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java:47]:
```suggestion
		boolean kerberState = PropertyUtils.getBoolean(Constants.HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE, false);
```

**Comment by yangyichao-mango** [comment]
Hi,
It maybe the error caused by embedded zk according the compile error info, and you can also try to rebase your branch from the newest dev branch and try run the pr ci again.

**Comment by felix-thinkingdata** [comment]
> Hi,
> It maybe the error caused by embedded zk according the compile error info, and you can also try to rebase your branch from the newest dev branch and try run the pr ci again.

i see  ，thx

**Comment by felix-thinkingdata** [comment]
> please revert the code format changes, and only keep your changes. it will make our submission records confusing.

**Comment by felix-thinkingdata** [comment]
> > please revert the code format changes, and only keep your changes. it will make our submission records confusing.



> please revert the code format changes, and only keep your changes. it will make our submission records confusing.

The code format changes have been completed ，Please check the code for me again，thank you

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java [hunk 2]
```diff
@@ -33,66 +33,86 @@
...
-		String responseContent = null;
-		CloseableHttpResponse response = null;
+    /**
+     * get http request content
+     *
+     * @param url url
+     * @return http get request response content
+     */
+    public static String get(String url) {
+	boolean kerberState = PropertyUtils.getBoolean(Constants.HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE, false);
```
Comment (yangyichao-mango) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java:46]: Hi~,
Because KERBER is only used for HADOOP_SECURITY_AUTHENTICATION, which belongs to a specific business logic. Therefore, the judgment of kerberstate suggests that it should be implemented in the business logic class not uilts class, and it is recommended to write a new get method specifically used to return KerberosHttpclient.

For example: If the user sets kerberstate to true, then when we use httputils.get in other places, a new kerberhttpclient will appear instead of a closed ablehttpclient.

-------

因为kerber只用于HADOOP_SECURITY_AUTHENTICATION，其属于一种特定的业务逻辑。所以kerberState的判断建议不要放在utils中，应该放在业务逻辑类中，并且建议再新写一个get方法专门用于返回KerberosHttpClient。

举例：如果用户设置了kerberState为true，那么我们在其他地方用到HttpUtils.get时，也会出现新建一个kerberHttpClient，而不是CloseableHttpClient。

If you have any question or suggestion, please put forward~

File: pom.xml [hunk 3]
```diff
@@ -807,9 +808,9 @@
                         <!--<include>**/server/master/register/MasterRegistryTest.java</include>-->
                         <include>**/server/master/AlertManagerTest.java</include>
                         <include>**/server/master/MasterCommandTest.java</include>
-                        <include>**/server/master/DependentTaskTest.java</include>
+                        <!--<include>**/server/master/DependentTaskTest.java</include>-->
```
Comment (yangyichao-mango) [inline pom.xml:811]: Hi~,
I have fixed the github action oom, please revert these changes.

Comment (felix-thinkingdata) [reply pom.xml:811]: > I have fixed the github action oom, please revert these changes.

Ok, let me modify it

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java (hunk 2 above)
Comment (felix-thinkingdata) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java]: It has been modified.

**Comment by yangyichao-mango** [comment]
Hi,
Good job,
I create an issue #3332  about HttpClient and KerberosHttpClient can further optimize singleton mode.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+	if (isDebug) {
+	    System.setProperty("sun.security.spnego.debug", "true");
+	    System.setProperty("sun.security.krb5.debug", "true");
+	}
+    }
+
+    public KerberosHttpClient(String principal, String keyTabLocation, String krb5Location, boolean isDebug) {
+	this(principal, keyTabLocation, isDebug);
+	System.setProperty("java.security.krb5.conf", krb5Location);
+    }
```
Comment (yangyichao-mango) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java:74]:
```suggestion
    public KerberosHttpClient(String principal, String keyTabLocation) {
        this(principal, keyTabLocation, false);
    }

    public KerberosHttpClient(String principal, String keyTabLocation, boolean isDebug) {
	this(principal, keyTabLocation, StringUtils.EMPTY, false);
    }

    public KerberosHttpClient(String principal, String keyTabLocation, String krb5Location, boolean isDebug) {
        this.principal = principal;
	this.keyTabLocation = keyTabLocation;
	System.setProperty("java.security.krb5.conf", krb5Location);
	if (isDebug) {
	    System.setProperty("sun.security.spnego.debug", "true");
	    System.setProperty("sun.security.krb5.debug", "true");
	}
    }
```

Comment (yangyichao-mango) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java:74]: The other part LGTM.

**Comment by felix-thinkingdata** [comment]
> Hi,
> Good job,
> I create an improvement issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode.


Can I continue to optimize my patch

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java (hunk 4 above)
Comment (felix-thinkingdata) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java:74]: Can I continue to optimize my patch

> Hi,
> Good job,
> I create an improvement issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode.

Continue optimizing in my Patch?

**Comment by felix-thinkingdata** [comment]
Should I continue to optimize my patch or  create a new patch?


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 19:49
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Hi,
 Good job,
 I create an issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode.

**Comment by yangyichao-mango** [comment]
> Should I continue to optimize my patch or create a new patch? 原始邮件 发件人: Yichao Yang<notifications@github.com> 收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com> 抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com> 发送时间: 2020年7月28日(周二) 19:49 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Hi, Good job, I create an issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi~,
I think this pr is just for fixing the bug of #3262 , and at present this pr LTGM.
But the issue #3332 is for httpClient singleton optimize, it is not for #3262 , so I create #3332 .
And it will be better if you are interested in optimizing the singleton in this pr, if you want to optimize it, please leave a message, after that I will close #3332 .

**Comment by felix-thinkingdata** [comment]
ok, I can do singleton model  optimization 。
I will also implement httpClient support for HTTPS, which I have some experience with.


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 21:53
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Should I continue to optimize my patch or create a new patch? 原始邮件 发件人: Yichao Yangnotifications@github.com 收件人: apache/incubator-dolphinschedulerincubator-dolphinscheduler@noreply.github.com 抄送: felix.wangfelix@thinkingdata.cn; State changestate_change@noreply.github.com 发送时间: 2020年7月28日(周二) 19:49 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Hi, Good job, I create an issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
Hi~,
 I think this pr is just for fixing the bug of #3262 , and at present this pr LTGM.
 But the issue #3332 is for httpClient singleton optimize, it is not for #3262 , so I create #3332 .
 And it will be better if you are interested in optimizing the singleton in this pr, if you want to optimize it, please leave a message, after that I will close #3332 .

**Comment by felix-thinkingdata** [comment]
Support for HTTPS means that httpClient can access httpClient normally in the case of HTTPS where the gift book is a self-built certificate。


 原始邮件 
发件人: felix<felix@thinkingdata.cn>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>; apache/incubator-dolphinscheduler<reply@reply.github.com>
抄送: State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 22:03
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


ok, I can do singleton model  optimization 。
I will also implement httpClient support for HTTPS, which I have some experience with.


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 21:53
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Should I continue to optimize my patch or create a new patch? 原始邮件 发件人: Yichao Yangnotifications@github.com 收件人: apache/incubator-dolphinschedulerincubator-dolphinscheduler@noreply.github.com 抄送: felix.wangfelix@thinkingdata.cn; State changestate_change@noreply.github.com 发送时间: 2020年7月28日(周二) 19:49 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Hi, Good job, I create an issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
Hi~,
 I think this pr is just for fixing the bug of #3262 , and at present this pr LTGM.
 But the issue #3332 is for httpClient singleton optimize, it is not for #3262 , so I create #3332 .
 And it will be better if you are interested in optimizing the singleton in this pr, if you want to optimize it, please leave a message, after that I will close #3332 .

**Comment by felix-thinkingdata** [comment]
Support for HTTPS means that httpClient can access httpClient normally in the case of HTTPS where the gift book is a self-built certificate。


中文：
 支持https 是指，在使用自建证书的情况下，也可以通过https url访问。一般自建证书程序会认为非安全会报错。


 原始邮件 
发件人: felix<felix@thinkingdata.cn>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>; apache/incubator-dolphinscheduler<reply@reply.github.com>
抄送: State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 22:07
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Support for HTTPS means that httpClient can access httpClient normally in the case of HTTPS where the gift book is a self-built certificate。


 原始邮件 
发件人: felix<felix@thinkingdata.cn>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>; apache/incubator-dolphinscheduler<reply@reply.github.com>
抄送: State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 22:03
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


ok, I can do singleton model  optimization 。
I will also implement httpClient support for HTTPS, which I have some experience with.


 原始邮件 
发件人: Yichao Yang<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: felix.wang<felix@thinkingdata.cn>; State change<state_change@noreply.github.com>
发送时间: 2020年7月28日(周二) 21:53
主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264)


Should I continue to optimize my patch or create a new patch? 原始邮件 发件人: Yichao Yangnotifications@github.com 收件人: apache/incubator-dolphinschedulerincubator-dolphinscheduler@noreply.github.com 抄送: felix.wangfelix@thinkingdata.cn; State changestate_change@noreply.github.com 发送时间: 2020年7月28日(周二) 19:49 主题: Re: [apache/incubator-dolphinscheduler] [Fix-3262][common] When yourequest the URL through applicationID to get the application status, youcannot get it if Kerberos authentication is enabled (#3264) Hi, Good job, I create an issue #3332 about HttpClient and KerberosHttpClient can further optimize singleton mode. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
Hi~,
 I think this pr is just for fixing the bug of #3262 , and at present this pr LTGM.
 But the issue #3332 is for httpClient singleton optimize, it is not for #3262 , so I create #3332 .
 And it will be better if you are interested in optimizing the singleton in this pr, if you want to optimize it, please leave a message, after that I will close #3332 .
