### PR TITLE
[FIX-#4617][LoggerServer] task log can not refresh in time

### LINKED ISSUE #4617: [Bug][LoggerServer] task log can not refresh in time
for example ，if 1s produce log size can not teet the default conditions --Constants.DEFAULT_LOG_ROWS_NUM（64）， and need to wait a long time。
image

### PR DESCRIPTION
**Pull request by 597365581**
fix [Bug][LoggerServer] task log can not refresh in time #4617

this closes #4617 

for example

#!/bin/bash
echo "hello world"
exec 10m
echo "hello world2"
if 1s produce log size can not meet the default conditions --Constants.DEFAULT_LOG_ROWS_NUM（64）， and need to wait a long time。 because while ((line = inReader.readLine()) != null) is a block method。

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java [hunk 1]
```diff
@@ -348,12 +348,14 @@ public void run() {
 
                     long lastFlushTime = System.currentTimeMillis();
 
-                    while ((line = inReader.readLine()) != null) {
+                    while ((line = inReader.readLine()) != null || logBuffer.size() > 0) {
```
Comment (chengshiwen) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: If line is `null`, an Exception will occur

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: If line is null  check logBuffer.size()>0 ，so lastFlushTime = flush(lastFlushTime); can have a chance to exec. old code  while ((line = inReader.readLine()) != null)   cause  lastFlushTime = flush(lastFlushTime);  have no chance to exec.

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: If line is null, an Exception will occur--->has modify

Comment (chengshiwen) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: Do you have tested it? And could you give why it can take effect?

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: yes   test is ok.   log  refresh in time

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: of course, test is ok so I commit this pr.

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: 兄弟，空了帮忙再review下，我现在改成了 inReader.readLine() 和logBuffer 处理 放在两个线程中处理了。

Comment (chengshiwen) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: @597365581 Maybe you should pass the **SonarCloud Code Analysis** at first

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: @chengshiwen of course，the SonarCloud Code Analysis must pass

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: @chengshiwen @dailidong  please help to review ，thanks

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: @lenboo please help to review ，thanks

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: @CalvinKirs  please help to review ，thanks

**Comment by CalvinKirs** [comment]
Do you have any questions about the design? @dailidong @liukunyuan @chengshiwen

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java [hunk 2]
```diff
@@ -336,32 +338,50 @@ private void clear() {
      */
     private void parseProcessOutput(Process process) {
         String threadLoggerInfoName = String.format(LoggerUtils.TASK_LOGGER_THREAD_NAME + "-%s", taskExecutionContext.getTaskAppId());
-        ExecutorService parseProcessOutputExecutorService = ThreadUtils.newDaemonSingleThreadExecutor(threadLoggerInfoName);
-        parseProcessOutputExecutorService.submit(new Runnable() {
+        ExecutorService getOutputLogService = ThreadUtils.newDaemonSingleThreadExecutor(threadLoggerInfoName + "-" + "getOutputLogService");
+        getOutputLogService.submit(new Runnable() {
```
Comment (CalvinKirs) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: Use lambda expression substitution, which will make the code look concise.

**Review by CalvinKirs — CHANGES_REQUESTED** [review]

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java [hunk 3]
```diff
@@ -336,32 +338,50 @@ private void clear() {
...
             @Override
             public void run() {
                 BufferedReader inReader = null;
 
                 try {
                     inReader = new BufferedReader(new InputStreamReader(process.getInputStream()));
```
Comment (CalvinKirs) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: Is there a problem here? Does ErrorStream cause blocking?

**Review by chengshiwen — APPROVED** [review]
There are already a lot of threads, I don’t think adding more threads is a good thing

**Review by chengshiwen — CHANGES_REQUESTED** [review]
There are already a lot of threads, I don’t think adding more threads is a good thing

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java (hunk 2 above)
Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: ok，code  had changed

Comment (CalvinKirs) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: ` 
parseProcessOutputExecutorService.submit(() -> {
            BufferedReader inReader = null;

            try {
                inReader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;

                long lastFlushTime = System.currentTimeMillis();

                while ((line = inReader.readLine()) != null) {
                    if (line.startsWith("${setValue(")) {
                        varPool.append(line.substring("${setValue(".length(), line.length() - 2));
                        varPool.append("$VarPool$");
                    } else {
                        logBuffer.add(line);
                        lastFlushTime = flush(lastFlushTime);
                    }
                }
            } catch (Exception e) {
                logger.error(e.getMessage(), e);
            } finally {
                clear();
                close(inReader);
            }
        });
`

Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: what？

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java (hunk 3 above)
Comment (597365581) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java]: I found DS code  has set processBuilder.redirectErrorStream(true);  before.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by davidzollo** [comment]
image
please sovle the conflicting files

**Comment by 597365581** [comment]
> image
> please sovle the conflicting files

ok, has sovled
image

**Comment by 597365581** [comment]
conflicts  has sovled

**Comment by 597365581** [comment]
> > image
> > please sovle the conflicting files
> 
> ok, has sovled
> image
conflicts has sovled

**Review by dailidong — APPROVED** [review]
+1
good job
