### PR TITLE
[FIX-2101]It solves the problem that the name of the branch will not change after the name of the branch is changed in the workflow page and instance page.

### LINKED ISSUE #2101: [BUG] After renaming the branch name, the name of Branch Flow does not change
更改任务名称后，分支流转的名称还是更改前的任务名称
image

**Which version of Dolphin Scheduler:**
 -[1.2.0_release]

### PR DESCRIPTION
**Pull request by zt-1997**
this closes #2101

### CODE REVIEW

**Comment by zt-1997** [comment]
My PR solves this issue
https://github.com/apache/incubator-dolphinscheduler/issues/2101

**Comment by zt-1997** [comment]
fix #2101

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java [hunk 1]
```diff
@@ -1990,4 +1990,60 @@ public String formatTaskAppId(TaskInstance taskInstance) {
...
+            String newName = taskNode.getName();
+            newNameTaskId.put(newId, newName);
+        }
+
+        // replace the previous conditionresult with a new one
+        List<TaskNode> tasks = processData.getTasks();
+        for (int i = 0; i < tasks.size(); i++) {
+            TaskNode taskNode = newTasks.get(i);
+            String type = taskNode.getType();
+            if ("CONDITIONS".equals(type)) {
```
Comment (lenboo) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java:2025]: you can use  enum TaskType instead of string.

**Comment by chengshiwen** [comment]
@zt-1997 What is the relationship between this PR and the duplicated PR #4543? Could you close one of them?
By the way, you should pass the **SonarCloud Code Analysis**

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/conditions/ConditionsParameters.java [hunk 2]
```diff
@@ -78,4 +78,11 @@ public void setSuccessNode(List<String> successNode) {
     public void setFailedNode(List<String> failedNode) {
         this.failedNode = failedNode;
     }
+
+    public String toJsonString() {
```
Comment (lenboo) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/conditions/ConditionsParameters.java:82]: you do not need toJsonString here. The JsonUtils already have this function.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java [hunk 3]
```diff
@@ -1990,4 +1992,57 @@ public String formatTaskAppId(TaskInstance taskInstance) {
...
+            String type = taskNode.getType().toLowerCase();
+            if (TaskType.CONDITIONS.getDescp().equals(type)) {
+                ConditionsParameters conditionsParameters = JSONUtils.parseObject(taskNode.getConditionResult(), ConditionsParameters.class);
+                String oldSuccessNodeName = conditionsParameters.getSuccessNode().get(0);
+                String oldFailedNodeName = conditionsParameters.getFailedNode().get(0);
+                String newSuccessNodeName = newNameTaskId.getOrDefault(oldNameTaskId.get(oldSuccessNodeName), "");
+                String newFailedNodeName = newNameTaskId.getOrDefault(oldNameTaskId.get(oldFailedNodeName), "");
+                if (!"".equals(newSuccessNodeName) || !"".equals(newFailedNodeName)) {
+                    ArrayList<String> successNode = new ArrayList<>();
+                    successNode.add("\"" + newSuccessNodeName + "\"");
```
Comment (lenboo) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java:2035]: i think it do not need "\" here

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java [hunk 4]
```diff
@@ -1990,4 +1992,57 @@ public String formatTaskAppId(TaskInstance taskInstance) {
...
+        // replace the previous conditionresult with a new one
+        List<TaskNode> tasks = processData.getTasks();
+        for (int i = 0; i < tasks.size(); i++) {
+            TaskNode taskNode = newTasks.get(i);
+            String type = taskNode.getType().toLowerCase();
+            if (TaskType.CONDITIONS.getDescp().equals(type)) {
+                ConditionsParameters conditionsParameters = JSONUtils.parseObject(taskNode.getConditionResult(), ConditionsParameters.class);
+                String oldSuccessNodeName = conditionsParameters.getSuccessNode().get(0);
+                String oldFailedNodeName = conditionsParameters.getFailedNode().get(0);
+                String newSuccessNodeName = newNameTaskId.getOrDefault(oldNameTaskId.get(oldSuccessNodeName), "");
```
Comment (lenboo) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java:2031]: what would happened when the old task is delete and add a new task?

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java [hunk 5]
```diff
@@ -1990,4 +1992,59 @@ public String formatTaskAppId(TaskInstance taskInstance) {
...
+            String newName = taskNode.getName();
+            newNameTaskId.put(newId, newName);
+        }
+
+        // replace the previous conditionresult with a new one
+        List<TaskNode> tasks = processData.getTasks();
+        for (int i = 0; i < tasks.size(); i++) {
+            TaskNode taskNode = newTasks.get(i);
+            String type = taskNode.getType().toLowerCase();
+            if (TaskType.CONDITIONS.getDescp().equals(type)) {
```
Comment (lenboo) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java:2027]: you can use equalsIgnoreCase instead of equals

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java [hunk 6]
```diff
@@ -459,6 +459,12 @@ private void addDependResultForTaskList(List<TaskInstance> taskInstanceList) thr
             if (tenant != null) {
                 processInstance.setTenantCode(tenant.getTenantCode());
             }
+            // get the processinstancejson before saving,and then save the name and taskid
+            String oldJson = processInstance.getProcessInstanceJson();
+            ProcessData oldProcessData = JSONUtils.parseObject(oldJson, ProcessData.class);
+            if (oldProcessData != null) {
```
Comment (lenboo) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java:465]: in order to reduce the complexity here, this null judge can be put into the ’changeJson‘

**Review by lenboo — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM
