### PR TITLE
[Bug][Common] read file garbled

### LINKED ISSUE #3478: [Bug][Common] read the file garbled
When reading the file, no encoding is specified, resulting in garbled code

image

image

### PR DESCRIPTION
**Pull request by BoYiZhang**
When reading the file, no encoding is specified, resulting in garbled code

issue:  close #3478

### CODE REVIEW

**Comment by BoYiZhang** [comment]
Because there is no Hadoop environment, code coverage can not be improved

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java [hunk 1]
```diff
@@ -21,18 +21,9 @@
...
-import java.io.ByteArrayOutputStream;
-import java.io.File;
-import java.io.FileOutputStream;
-import java.io.FileWriter;
-import java.io.IOException;
-import java.io.InputStream;
-import java.io.OutputStream;
-import java.io.StringReader;
-import java.io.UnsupportedEncodingException;
+import java.io.*;
```
Comment (yangyichao-mango) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:24]: Please configure checkstyle and code-style, ctrl+L will automatic to format the code.

Comment (yangyichao-mango) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:24]: Please configure checkstyle and code-style, ctrl+L will automatic to format the code.

**Review by yangyichao-mango — DISMISSED** [review]

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java (hunk 1 above)
Comment (BoYiZhang) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:24]: Is this mandatory?

I personally don't like controls like AutoFormat

After a lot of time, there will be uncontrollable formatting

Comment (yangyichao-mango) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:24]: It is mandatory, and there is the reason why we need checkstyle.[1]

Actually, checkstyle automatic format will make the code more controllable.
Maybe when we review code, it will add a little work, but the format and clear code will help user to read it more easier and quickly.

For example in this pr,
There is a lot unnecessary changes about import in this pr, if we use checkstyle auto import, there will not have a lot of changes about import.

[1] https://lists.apache.org/thread.html/ra65d23640728b12a8a1102495202ff066accfe99e80e5c694e093d49%40%3Cdev.dolphinscheduler.apache.org%3E

**Review by CalvinKirs — APPROVED** [review]
LGTM,Please you confirm again @dailidong @qiaozhanwei

**Comment by CalvinKirs** [comment]
hi, why did you turn this off?

**Comment by BoYiZhang** [comment]
> hi, why did you turn this off?

Because there was no merge and no feedback for a long time, it was turned off directly

**Comment by CalvinKirs** [comment]
> > hi, why did you turn this off?
> 
> Because there was no merge and no feedback for a long time, it was turned off directly

I saw it last time, there is no problem, can you reopen it, I will confirm again and merge as soon as possible (if there is no problem)

**Review by CalvinKirs — APPROVED** [review]
looks good to me
